services:
  postgres:
    image: postgres:latest
    container_name: m42hub-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  m42hub:
    build: .
    container_name: m42hub-api
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - app_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  app_data: