spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.stat: DEBUG

m42hub:
  security:
    secret: ${SECRET}
    cookie-secure: false

cors:
  allowed-origins:
    - http://localhost:4200
    - https://www.m42hub.com

imgBB:
  upload-url: ${IMGBB_UPLOAD_URL}